# Generated by Django 3.2.5 on 2021-12-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Done', 'Done'), ('Archived', 'Archived')], default='Active', max_length=12)),
                ('Title', models.CharField(max_length=250)),
            ],
        ),
    ]
