# Generated by Django 3.2.5 on 2021-12-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskes', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Done', 'Done'), ('Archived', 'Archived')], default='Draft', max_length=12),
        ),
    ]
